var All=[
    {
        id:1,
        title:"Interview Me",
         name:"Prestige Challenge",
        github:'www.com',
        link:"aa.com",
        summary:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi ut perspiciatis placeat quae ducimus eius",
  description:"        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo ipsum cupiditate labore quibusdam eaque magni earum porro id aliquam explicabo. Accusamus iure minus molestias tempora cumque sequi dolorum. Est, placeat. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis dolore quasi accusantium, placeat, alias, debitis blanditiis quisquam nulla natus recusandae ex necessitatibus sunt. Cupiditate officia possimus commodi, incidunt dolorem sunt. Consectetur sunt minima dolor culpa reprehenderit, pariatur nisi est sed eos nam dignissimos reiciendis? Et, similique dicta? Eius laudantium perspiciatis consequuntur voluptates sequi iusto temporibus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus ducimus accusamus eos accusantium! Modi voluptate necessitatibus numquam tenetur praesentium dolores fugit deserunt, quasi sed esse? Atque, ipsa nihil! Ut minima accusamus soluta omnis. Assumenda quis deleniti veniam cum ipsum itaque enim expedita error facilis dolorum at reiciendis, non quos sit asperiores doloremque quod mollitia vitae, vero blanditiis dolores dicta voluptatibus animi minima. Id quae laborum molestias error, placeat officia! Ipsam, molestiae eaque aliquam dolor placeat architecto reiciendis molestias vero, tempora nulla cum ipsum voluptatum est ea culpa numquam sit tempore cumque aliquid doloribus, repudiandae nisi. Illo eos dolor animi blanditiis    Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur repudiandae nulla quasi, nisi vel voluptatem excepturi voluptatibus similique provident temporibus eveniet veniam vitae cupiditate at pariatur, ipsum illo. Debitis, illo.s. Assumenda quis deleniti veniam cum ipsum itaque enim expedita error facilis dolorum at reiciendis, non quos sit asperiores doloremque quod mollitia vitae, vero blanditiis dolores dicta voluptatibus animi minima. Id quae laborum molestias error, placeat officia! Ipsam, molestiae eaque aliquam dolor placeat architecto reiciendis molestias vero, tempora nulla cum ipsum voluptatum est ea culpa numquam sit tempore cumque aliquid doloribus, repudiandae nisi. Illo eos",

        image:'../images/InterviewMe.png'
        ,favourite:1,startdate:"2021-03-12",enddate:"2021-03-12"

    },
    {
        id:2,  title:"Lorem ipsum ",
        name:"Lorem ipsum ",
       github:'www.com',
       link:"aa.com",
       summary:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi ut perspiciatis placeat quae ducimus eius",
  description:"        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo ipsum cupiditate labore quibusdam eaque magni earum porro id aliquam explicabo. Accusamus iure minus molestias tempora cumque sequi dolorum. Est, placeat. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis dolore quasi accusantium, placeat, alias, debitis blanditiis quisquam nulla natus recusandae ex necessitatibus sunt. Cupiditate officia possimus commodi, incidunt dolorem sunt. Consectetur sunt minima dolor culpa reprehenderit, pariatur nisi est sed eos nam dignissimos reiciendis? Et, similique dicta? Eius laudantium perspiciatis consequuntur voluptates sequi iusto temporibus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus ducimus accusamus eos accusantium! Modi voluptate necessitatibus numquam tenetur praesentium dolores fugit deserunt, quasi sed esse? Atque, ipsa nihil! Ut minima accusamus soluta omnis. Assumenda quis deleniti veniam cum ipsum itaque enim expedita error facilis dolorum at reiciendis, non quos sit asperiores doloremque quod mollitia vitae, vero blanditiis dolores dicta voluptatibus animi minima. Id quae laborum molestias error, placeat officia! Ipsam, molestiae eaque aliquam dolor placeat architecto reiciendis molestias vero, tempora nulla cum ipsum voluptatum est ea culpa numquam sit tempore cumque aliquid doloribus, repudiandae nisi. Illo eos dolor animi blanditiis    Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur repudiandae nulla quasi, nisi vel voluptatem excepturi voluptatibus similique provident temporibus eveniet veniam vitae cupiditate at pariatur, ipsum illo. Debitis, illo.s. Assumenda quis deleniti veniam cum ipsum itaque enim expedita error facilis dolorum at reiciendis, non quos sit asperiores doloremque quod mollitia vitae, vero blanditiis dolores dicta voluptatibus animi minima. Id quae laborum molestias error, placeat officia! Ipsam, molestiae eaque aliquam dolor placeat architecto reiciendis molestias vero, tempora nulla cum ipsum voluptatum est ea culpa numquam sit tempore cumque aliquid doloribus, repudiandae nisi. Illo eos",

        image:'../images/Lorem ipsum.png',
        favourite:1,startdate:"2022-03-12",enddate:"2022-03-12"
    },
    {
        id:3,  title:"Potter ipsum ",
        name:"Potter Ipsum",
       github:'www.com',
       link:"aa.com",
       summary:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi ut perspiciatis placeat quae ducimus eius",
  description:"        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo ipsum cupiditate labore quibusdam eaque magni earum porro id aliquam explicabo. Accusamus iure minus molestias tempora cumque sequi dolorum. Est, placeat. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis dolore quasi accusantium, placeat, alias, debitis blanditiis quisquam nulla natus recusandae ex necessitatibus sunt. Cupiditate officia possimus commodi, incidunt dolorem sunt. Consectetur sunt minima dolor culpa reprehenderit, pariatur nisi est sed eos nam dignissimos reiciendis? Et, similique dicta? Eius laudantium perspiciatis consequuntur voluptates sequi iusto temporibus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus ducimus accusamus eos accusantium! Modi voluptate necessitatibus numquam tenetur praesentium dolores fugit deserunt, quasi sed esse? Atque, ipsa nihil! Ut minima accusamus soluta omnis. Assumenda quis deleniti veniam cum ipsum itaque enim expedita error facilis dolorum at reiciendis, non quos sit asperiores doloremque quod mollitia vitae, vero blanditiis dolores dicta voluptatibus animi minima. Id quae laborum molestias error, placeat officia! Ipsam, molestiae eaque aliquam dolor placeat architecto reiciendis molestias vero, tempora nulla cum ipsum voluptatum est ea culpa numquam sit tempore cumque aliquid doloribus, repudiandae nisi. Illo eos dolor animi blanditiis    Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur repudiandae nulla quasi, nisi vel voluptatem excepturi voluptatibus similique provident temporibus eveniet veniam vitae cupiditate at pariatur, ipsum illo. Debitis, illo.s. Assumenda quis deleniti veniam cum ipsum itaque enim expedita error facilis dolorum at reiciendis, non quos sit asperiores doloremque quod mollitia vitae, vero blanditiis dolores dicta voluptatibus animi minima. Id quae laborum molestias error, placeat officia! Ipsam, molestiae eaque aliquam dolor placeat architecto reiciendis molestias vero, tempora nulla cum ipsum voluptatum est ea culpa numquam sit tempore cumque aliquid doloribus, repudiandae nisi. Illo eos",

        image:'../images/Office ipsum.png'
        ,favourite:0,startdate:"2023-03-12",enddate:"2023-03-12"
    },
    {
        id:4,  title:"Pizza Lorem",
        name:"Pizza Lorem",
       github:'www.com',
       link:"aa.com",
       summary:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi ut perspiciatis placeat quae ducimus eius",
        description:"        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo ipsum cupiditate labore quibusdam eaque magni earum porro id aliquam explicabo. Accusamus iure minus molestias tempora cumque sequi dolorum. Est, placeat. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis dolore quasi accusantium, placeat, alias, debitis blanditiis quisquam nulla natus recusandae ex necessitatibus sunt. Cupiditate officia possimus commodi, incidunt dolorem sunt. Consectetur sunt minima dolor culpa reprehenderit, pariatur nisi est sed eos nam dignissimos reiciendis? Et, similique dicta? Eius laudantium perspiciatis consequuntur voluptates sequi iusto temporibus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus ducimus accusamus eos accusantium! Modi voluptate necessitatibus numquam tenetur praesentium dolores fugit deserunt, quasi sed esse? Atque, ipsa nihil! Ut minima accusamus soluta omnis. Assumenda quis deleniti veniam cum ipsum itaque enim expedita error facilis dolorum at reiciendis, non quos sit asperiores doloremque quod mollitia vitae, vero blanditiis dolores dicta voluptatibus animi minima. Id quae laborum molestias error, placeat officia! Ipsam, molestiae eaque aliquam dolor placeat architecto reiciendis molestias vero, tempora nulla cum ipsum voluptatum est ea culpa numquam sit tempore cumque aliquid doloribus, repudiandae nisi. Illo eos dolor animi blanditiis    Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur repudiandae nulla quasi, nisi vel voluptatem excepturi voluptatibus similique provident temporibus eveniet veniam vitae cupiditate at pariatur, ipsum illo. Debitis, illo.s. Assumenda quis deleniti veniam cum ipsum itaque enim expedita error facilis dolorum at reiciendis, non quos sit asperiores doloremque quod mollitia vitae, vero blanditiis dolores dicta voluptatibus animi minima. Id quae laborum molestias error, placeat officia! Ipsam, molestiae eaque aliquam dolor placeat architecto reiciendis molestias vero, tempora nulla cum ipsum voluptatum est ea culpa numquam sit tempore cumque aliquid doloribus, repudiandae nisi. Illo eos",

        image:'../images/Pirate ipsum.jpg'
        ,favourite:0,startdate:"2014-03-12",enddate:"2014-03-12"
    },
    {
        id:5,  title:"Figma Ipsum",
        name:"Figma Ipsum",
       github:'www.com',
       link:"aa.com",
       summary:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi ut perspiciatis placeat quae ducimus eius",
  description:"        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo ipsum cupiditate labore quibusdam eaque magni earum porro id aliquam explicabo. Accusamus iure minus molestias tempora cumque sequi dolorum. Est, placeat. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis dolore quasi accusantium, placeat, alias, debitis blanditiis quisquam nulla natus recusandae ex necessitatibus sunt. Cupiditate officia possimus commodi, incidunt dolorem sunt. Consectetur sunt minima dolor culpa reprehenderit, pariatur nisi est sed eos nam dignissimos reiciendis? Et, similique dicta? Eius laudantium perspiciatis consequuntur voluptates sequi iusto temporibus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus ducimus accusamus eos accusantium! Modi voluptate necessitatibus numquam tenetur praesentium dolores fugit deserunt, quasi sed esse? Atque, ipsa nihil! Ut minima accusamus soluta omnis. Assumenda quis deleniti veniam cum ipsum itaque enim expedita error facilis dolorum at reiciendis, non quos sit asperiores doloremque quod mollitia vitae, vero blanditiis dolores dicta voluptatibus animi minima. Id quae laborum molestias error, placeat officia! Ipsam, molestiae eaque aliquam dolor placeat architecto reiciendis molestias vero, tempora nulla cum ipsum voluptatum est ea culpa numquam sit tempore cumque aliquid doloribus, repudiandae nisi. Illo eos dolor animi blanditiis    Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur repudiandae nulla quasi, nisi vel voluptatem excepturi voluptatibus similique provident temporibus eveniet veniam vitae cupiditate at pariatur, ipsum illo. Debitis, illo.s. Assumenda quis deleniti veniam cum ipsum itaque enim expedita error facilis dolorum at reiciendis, non quos sit asperiores doloremque quod mollitia vitae, vero blanditiis dolores dicta voluptatibus animi minima. Id quae laborum molestias error, placeat officia! Ipsam, molestiae eaque aliquam dolor placeat architecto reiciendis molestias vero, tempora nulla cum ipsum voluptatum est ea culpa numquam sit tempore cumque aliquid doloribus, repudiandae nisi. Illo eos",

        image:'../images/Pizza ipsum.png'
        ,favourite:0,startdate:"2025-03-12",enddate:"2025-03-12"
    },
    {
        id:6,  title:"Office Ispum",
        name:"Office Ispum",
       github:'www.com',
       link:"aa.com",
       summary:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi ut perspiciatis placeat quae ducimus eius",
         description:"        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo ipsum cupiditate labore quibusdam eaque magni earum porro id aliquam explicabo. Accusamus iure minus molestias tempora cumque sequi dolorum. Est, placeat. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis dolore quasi accusantium, placeat, alias, debitis blanditiis quisquam nulla natus recusandae ex necessitatibus sunt. Cupiditate officia possimus commodi, incidunt dolorem sunt. Consectetur sunt minima dolor culpa reprehenderit, pariatur nisi est sed eos nam dignissimos reiciendis? Et, similique dicta? Eius laudantium perspiciatis consequuntur voluptates sequi iusto temporibus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus ducimus accusamus eos accusantium! Modi voluptate necessitatibus numquam tenetur praesentium dolores fugit deserunt, quasi sed esse? Atque, ipsa nihil! Ut minima accusamus soluta omnis. Assumenda quis deleniti veniam cum ipsum itaque enim expedita error facilis dolorum at reiciendis, non quos sit asperiores doloremque quod mollitia vitae, vero blanditiis dolores dicta voluptatibus animi minima. Id quae laborum molestias error, placeat officia! Ipsam, molestiae eaque aliquam dolor placeat architecto reiciendis molestias vero, tempora nulla cum ipsum voluptatum est ea culpa numquam sit tempore cumque aliquid doloribus, repudiandae nisi. Illo eos dolor animi blanditiis    Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur repudiandae nulla quasi, nisi vel voluptatem excepturi voluptatibus similique provident temporibus eveniet veniam vitae cupiditate at pariatur, ipsum illo. Debitis, illo.s. Assumenda quis deleniti veniam cum ipsum itaque enim expedita error facilis dolorum at reiciendis, non quos sit asperiores doloremque quod mollitia vitae, vero blanditiis dolores dicta voluptatibus animi minima. Id quae laborum molestias error, placeat officia! Ipsam, molestiae eaque aliquam dolor placeat architecto reiciendis molestias vero, tempora nulla cum ipsum voluptatum est ea culpa numquam sit tempore cumque aliquid doloribus, repudiandae nisi. Illo eos",

        image:'../images/Potter ipsum.png'
        ,favourite:0,startdate:"2019-03-12",enddate:"2019-03-12"
    }
    
]
export default All;